name: ground
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlicffi=1.1.0.0=py310hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h4eded50_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.20.0=py310h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310h591646f_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_1
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py310h06a4308_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py310h7c4b9e2_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310h06a4308_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.45.5
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.1
      - deepspeed==0.18.2
      - dill==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - fastapi==0.121.3
      - ffmpy==1.0.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gradio==4.16.0
      - gradio-client==0.8.1
      - grpcio==1.76.0
      - h11==0.14.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.36.0
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - latex2mathml==3.78.1
      - llava==1.2.2.post1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - narwhals==2.12.0
      - ninja==1.13.0
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.12.0.88
      - orjson==3.11.4
      - pandas==2.3.3
      - peft==0.4.0
      - pillow==10.4.0
      - protobuf==3.20.3
      - py-cpuinfo==9.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyparsing==3.2.5
      - python-multipart==0.0.20
      - pytz==2025.2
      - referencing==0.37.0
      - rich==14.2.0
      - rpds-py==0.29.0
      - ruff==0.14.6
      - scikit-learn==1.2.2
      - scipy==1.15.3
      - segment-anything==1.0
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - shapely==2.1.2
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - starlette==0.50.0
      - svgwrite==1.4.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==0.6.13
      - tokenizers==0.15.1
      - tomlkit==0.12.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - transformers==4.37.2
      - triton==3.3.1
      - typer==0.20.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
      - wavedrom==2.0.3.post3
      - websockets==11.0.3
      - werkzeug==3.1.3
      - yarl==1.22.0
prefix: /home/teaching/anaconda3/envs/ground
